//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArchiveTranscriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchiveTranscriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.ArchiveTranscriptResources", typeof(ArchiveTranscriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О факте несчастных случаев на производстве.
        /// </summary>
        public static string ArchiveSvcAccidentsRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcAccidentsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О решении, постановлений акимата города Астаны (горисполкома) (о предоставлении земли, об опекунстве и.т.д.) (до 2010 года).
        /// </summary>
        public static string ArchiveSvcAkimatDecisionsRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcAkimatDecisionsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для получения оригинала архивной справки необходимо обратиться в Государственный архив г.Астана.
        /// </summary>
        public static string ArchiveSvcAlert {
            get {
                return ResourceManager.GetString("ArchiveSvcAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об актах гражданского состояния (до 1936 года).
        /// </summary>
        public static string ArchiveSvcCivilStatusRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcCivilStatusRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О праве на наследство, договор купли-продажи, договор дарения и т.д..
        /// </summary>
        public static string ArchiveSvcInheritanceRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcInheritanceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О решении суда.
        /// </summary>
        public static string ArchiveSvcJudgementRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcJudgementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О факте обучения.
        /// </summary>
        public static string ArchiveSvcLearningRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcLearningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О факте легализации недвижимого имущества.
        /// </summary>
        public static string ArchiveSvcLegalizationRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcLegalizationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О пребывании в Приюте для несовершеннолетних в Астане (с 2000 года).
        /// </summary>
        public static string ArchiveSvcOrphanageRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcOrphanageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочее.
        /// </summary>
        public static string ArchiveSvcOthersRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcOthersRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О факте приватизации.
        /// </summary>
        public static string ArchiveSvcPrivatizationRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcPrivatizationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О переименовании.
        /// </summary>
        public static string ArchiveSvcRenameRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcRenameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О заработной плате.
        /// </summary>
        public static string ArchiveSvcSalaryRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcSalaryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивная справка либо мотивированный ответ об отказе.
        /// </summary>
        public static string ArchiveSvcServiceResult {
            get {
                return ResourceManager.GetString("ArchiveSvcServiceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О технико-экономических показателях (акт ввода в эксплуатацию зданий, сооружений, многоквартирных домов.
        /// </summary>
        public static string ArchiveSvcTechnicalDetailsRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcTechnicalDetailsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О факте работы.
        /// </summary>
        public static string ArchiveSvcWorkRequest {
            get {
                return ResourceManager.GetString("ArchiveSvcWorkRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивная справка.
        /// </summary>
        public static string ArchiveTranscript {
            get {
                return ResourceManager.GetString("ArchiveTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласование решения Отказать в выдаче архивной справки.
        /// </summary>
        public static string ArchiveTranscriptDenyStep {
            get {
                return ResourceManager.GetString("ArchiveTranscriptDenyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка справки.
        /// </summary>
        public static string ArchiveTranscriptProcessStep {
            get {
                return ResourceManager.GetString("ArchiveTranscriptProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача архивных справок.
        /// </summary>
        public static string ArchiveTranscriptsService {
            get {
                return ResourceManager.GetString("ArchiveTranscriptsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГУ &quot;Государственный архив города Астаны&quot;.
        /// </summary>
        public static string AstanaGovArchive {
            get {
                return ResourceManager.GetString("AstanaGovArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать в выдаче архивной справки.
        /// </summary>
        public static string DenyArchTranscriptTask {
            get {
                return ResourceManager.GetString("DenyArchTranscriptTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за получением архивной справки об учебе к запросу необходимо приложить копии паспорта, диплома (в случае утраты диплома при заполнении заявления необходимо указать: наименование учебного заведения, точные даты учебы, специальность, факультет, отделение).
        /// </summary>
        public static string DocumentForLearning {
            get {
                return ResourceManager.GetString("DocumentForLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия удостоверения личности.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за получением архивной справки (выписки) по вопросам легализации и приватизации к запросу приложить копии договора, решения (в случае отсутствия договора о приватизации, при заполнении заявления необходимо максимально точно указать год приватизации, фамилия гражданина приватизируемой квартиры и адрес приватизированной квартиры на момент приватизации; в случае отсутствия решения указать на имя кого вынесено решение, район (Алматы, Сарыарка), наименование легализуемого объекта, адрес и дата.
        /// </summary>
        public static string DocumentLegalization {
            get {
                return ResourceManager.GetString("DocumentLegalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в случае запроса данных на третье лицо необходима электронная копия нотариально засвидетельствованной доверенности.
        /// </summary>
        public static string DocumentPoA {
            get {
                return ResourceManager.GetString("DocumentPoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за получением архивной справки о стаже и заработной плате к запросу необходимо приложить копии удостоверения личности (паспорта), трудовой книжки (в случае утраты трудовой книжки при заполнении заявления необходимо максимально точно указать даты приема и увольнения, отдел (цех), названия должностей, местонахождение организации, за какие годы необходима справка о зарплате.
        /// </summary>
        public static string DocumentWorkbook {
            get {
                return ResourceManager.GetString("DocumentWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за получением архивной справки о рождении, браке, смерти в запросе необходимо указать место рождения, точный год, церковь, в которой произведена метрическая записи.
        /// </summary>
        public static string DocumentZags {
            get {
                return ResourceManager.GetString("DocumentZags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдать архивную справку.
        /// </summary>
        public static string GiveArchTranscriptTask {
            get {
                return ResourceManager.GetString("GiveArchTranscriptTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздел: {0}. файл: {1} - не прошел проверку.
        /// </summary>
        public static string MsgFileValidationFailed {
            get {
                return ResourceManager.GetString("MsgFileValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздел: {0} - обязательный для заполнения.
        /// </summary>
        public static string MsgSectionIsRequired {
            get {
                return ResourceManager.GetString("MsgSectionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пояснение запроса.
        /// </summary>
        public static string RequestComment {
            get {
                return ResourceManager.GetString("RequestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характер запроса сведений.
        /// </summary>
        public static string RequestedInfo {
            get {
                return ResourceManager.GetString("RequestedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куда и с какой целью запрашиваются сведения.
        /// </summary>
        public static string RequestPurpose {
            get {
                return ResourceManager.GetString("RequestPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия удостоверения личности.
        /// </summary>
        public static string ScanOfIdentification {
            get {
                return ResourceManager.GetString("ScanOfIdentification", resourceCulture);
            }
        }
    }
}
