//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CitizenReceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitizenReceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.CitizenReceptionResources", typeof(CitizenReceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записан.
        /// </summary>
        public static string CitResSvcAccepted {
            get {
                return ResourceManager.GetString("CitResSvcAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнено в ЭДО.
        /// </summary>
        public static string CitResSvcDone {
            get {
                return ResourceManager.GetString("CitResSvcDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не перенесено.
        /// </summary>
        public static string CitResSvcNotTransfered {
            get {
                return ResourceManager.GetString("CitResSvcNotTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыт.
        /// </summary>
        public static string CitResSvcOpen {
            get {
                return ResourceManager.GetString("CitResSvcOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрирован.
        /// </summary>
        public static string CitResSvcRegistered {
            get {
                return ResourceManager.GetString("CitResSvcRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонен.
        /// </summary>
        public static string CitResSvcRejected {
            get {
                return ResourceManager.GetString("CitResSvcRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенесено.
        /// </summary>
        public static string CitResSvcTransfered {
            get {
                return ResourceManager.GetString("CitResSvcTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание(вопрос).
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата записи на прием.
        /// </summary>
        public static string DateOfReception {
            get {
                return ResourceManager.GetString("DateOfReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО ведущего прием.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность ведущего прием.
        /// </summary>
        public static string EmployeePosition {
            get {
                return ResourceManager.GetString("EmployeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование ГУ.
        /// </summary>
        public static string GovernmentOrganizationName {
            get {
                return ResourceManager.GetString("GovernmentOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на должностные полномочия.
        /// </summary>
        public static string LinkToRights {
            get {
                return ResourceManager.GetString("LinkToRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория вопроса.
        /// </summary>
        public static string QuestionCategory {
            get {
                return ResourceManager.GetString("QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием граждан.
        /// </summary>
        public static string ReceptionOfCitezens {
            get {
                return ResourceManager.GetString("ReceptionOfCitezens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График приема.
        /// </summary>
        public static string ReceptionTimetable {
            get {
                return ResourceManager.GetString("ReceptionTimetable", resourceCulture);
            }
        }
    }
}
