//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonEnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonEnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.CommonEnumResources", typeof(CommonEnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыто.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия удостоверения личности.
        /// </summary>
        public static string CopyOfIdentification {
            get {
                return ResourceManager.GetString("CopyOfIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвалид.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LanguageRu {
            get {
                return ResourceManager.GetString("LanguageRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Казахский.
        /// </summary>
        public static string LanguageКz {
            get {
                return ResourceManager.GetString("LanguageКz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учащийся.
        /// </summary>
        public static string Learner {
            get {
                return ResourceManager.GetString("Learner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическое лицо.
        /// </summary>
        public static string LegalPerson {
            get {
                return ResourceManager.GetString("LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие документы.
        /// </summary>
        public static string OtherDocuments {
            get {
                return ResourceManager.GetString("OtherDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пенсионер.
        /// </summary>
        public static string Pensioner {
            get {
                return ResourceManager.GetString("Pensioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дошкольник.
        /// </summary>
        public static string PreschoolChild {
            get {
                return ResourceManager.GetString("PreschoolChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическое лицо.
        /// </summary>
        public static string PrivatePerson {
            get {
                return ResourceManager.GetString("PrivatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безработный.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работающий.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
