//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonFamRelationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonFamRelationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.CommonFamRelationsResources", typeof(CommonFamRelationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тетя.
        /// </summary>
        public static string Aunt {
            get {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брат.
        /// </summary>
        public static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дочь.
        /// </summary>
        public static string Daughter {
            get {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отец.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дедушка.
        /// </summary>
        public static string Granddad {
            get {
                return ResourceManager.GetString("Granddad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бабушка.
        /// </summary>
        public static string Grandmother {
            get {
                return ResourceManager.GetString("Grandmother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мать.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет родства.
        /// </summary>
        public static string NoRelationship {
            get {
                return ResourceManager.GetString("NoRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сестра.
        /// </summary>
        public static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сын.
        /// </summary>
        public static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супруг(а).
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дядя.
        /// </summary>
        public static string Uncle {
            get {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
    }
}
