//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DayCareQueueResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DayCareQueueResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.DayCareQueueResources", typeof(DayCareQueueResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить свободные места.
        /// </summary>
        public static string AddFreePlaces {
            get {
                return ResourceManager.GetString("AddFreePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес детской дошкольной организации.
        /// </summary>
        public static string AddressChildSchoolOrganizations {
            get {
                return ResourceManager.GetString("AddressChildSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст ребенка не должен превышать 7 лет.
        /// </summary>
        public static string AgeLessSeven {
            get {
                return ResourceManager.GetString("AgeLessSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При получении направления в поселковый детский сад, Вы автоматически снимаетесь с очереди.
        /// </summary>
        public static string AutoExitFromQueue {
            get {
                return ResourceManager.GetString("AutoExitFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическая.
        /// </summary>
        public static string Automated {
            get {
                return ResourceManager.GetString("Automated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАРТОЧКА ДЕТСКОГО САДА ПРЕДОСТАВЛЕННАЯ ПОРТАЛОМ ЭЛЕКТРОННЫХ УСЛУГ АКИМАТА ГОРОДА АСТАНА.
        /// </summary>
        public static string CartChildFromEService {
            get {
                return ResourceManager.GetString("CartChildFromEService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный ребенок уже стоит в очереди.
        /// </summary>
        public static string ChildInQueue {
            get {
                return ResourceManager.GetString("ChildInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ребенок уже стоит в очереди.
        /// </summary>
        public static string ChildNowInQueue {
            get {
                return ResourceManager.GetString("ChildNowInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор государственного ДДО.
        /// </summary>
        public static string ChooseGovDdo {
            get {
                return ResourceManager.GetString("ChooseGovDdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор мини-центра.
        /// </summary>
        public static string ChooseMiniCenter {
            get {
                return ResourceManager.GetString("ChooseMiniCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дошкольный обучающий мини-центр.
        /// </summary>
        public static string ChoosePreSchoolMiniCentr {
            get {
                return ResourceManager.GetString("ChoosePreSchoolMiniCentr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать поселковую дошкольную организацию.
        /// </summary>
        public static string ChoosePreSchoolOrganizations {
            get {
                return ResourceManager.GetString("ChoosePreSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор частной детской дошкольной организации.
        /// </summary>
        public static string ChoosePrivateDdo {
            get {
                return ResourceManager.GetString("ChoosePrivateDdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать государственный детский сад.
        /// </summary>
        public static string ChoosePublicKind {
            get {
                return ResourceManager.GetString("ChoosePublicKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор дошкольной организации поселкового типа.
        /// </summary>
        public static string ChooseVillagedDdo {
            get {
                return ResourceManager.GetString("ChooseVillagedDdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База свободных мест в ДДО.
        /// </summary>
        public static string DatabaseFreePlace {
            get {
                return ResourceManager.GetString("DatabaseFreePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куда выдано направление.
        /// </summary>
        public static string DayCareInfo {
            get {
                return ResourceManager.GetString("DayCareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список детских дошкольных организации.
        /// </summary>
        public static string DayCareList {
            get {
                return ResourceManager.GetString("DayCareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН владельца ДДО.
        /// </summary>
        public static string DayCareOwnerIin {
            get {
                return ResourceManager.GetString("DayCareOwnerIin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Перейти к базе свободных мест ДДО.
        /// </summary>
        public static string DayCareOwnerWorkplaceLinkToDdoBase {
            get {
                return ResourceManager.GetString("DayCareOwnerWorkplaceLinkToDdoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий кабинет сотрудника ДДО.
        /// </summary>
        public static string DayCareOwnerWorkplaceTitle {
            get {
                return ResourceManager.GetString("DayCareOwnerWorkplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После подтверждения, сохраненные данные редактированию не подлежат.
        /// </summary>
        public static string DayCareQueueResources_AfterAgree {
            get {
                return ResourceManager.GetString("DayCareQueueResources_AfterAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены в корректности введенных данных?.
        /// </summary>
        public static string DayCareQueueResources_AreYouSure {
            get {
                return ResourceManager.GetString("DayCareQueueResources_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановки на очередь.
        /// </summary>
        public static string DayOfQueue {
            get {
                return ResourceManager.GetString("DayOfQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН владельца ДДО.
        /// </summary>
        public static string DDOOwnerIIn {
            get {
                return ResourceManager.GetString("DDOOwnerIIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дети сотрудников специальных государственных органов.
        /// </summary>
        public static string DdoPrevGosOrgan {
            get {
                return ResourceManager.GetString("DdoPrevGosOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвалиды.
        /// </summary>
        public static string DdoPrevInvalid {
            get {
                return ResourceManager.GetString("DdoPrevInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многодетная семья.
        /// </summary>
        public static string DdoPrevLargeFam {
            get {
                return ResourceManager.GetString("DdoPrevLargeFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военнослужащие.
        /// </summary>
        public static string DdoPrevMilitary {
            get {
                return ResourceManager.GetString("DdoPrevMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без льготы.
        /// </summary>
        public static string DdoPrevNotPrivilaged {
            get {
                return ResourceManager.GetString("DdoPrevNotPrivilaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дети-сироты.
        /// </summary>
        public static string DdoPrevOrphans {
            get {
                return ResourceManager.GetString("DdoPrevOrphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Льготник.
        /// </summary>
        public static string DdoPrevPrivilaged {
            get {
                return ResourceManager.GetString("DdoPrevPrivilaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировано.
        /// </summary>
        public static string DdoStateBlocked {
            get {
                return ResourceManager.GetString("DdoStateBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдано направление.
        /// </summary>
        public static string DdoStateDirected {
            get {
                return ResourceManager.GetString("DdoStateDirected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В очереди.
        /// </summary>
        public static string DdoStateInQueue {
            get {
                return ResourceManager.GetString("DdoStateInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направлено уведомление.
        /// </summary>
        public static string DdoStateNoticed {
            get {
                return ResourceManager.GetString("DdoStateNoticed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снят с очереди.
        /// </summary>
        public static string DdoStateRemoved {
            get {
                return ResourceManager.GetString("DdoStateRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип детского сада.
        /// </summary>
        public static string DDOType {
            get {
                return ResourceManager.GetString("DDOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Государственные детские сады.
        /// </summary>
        public static string DdoTypeGovernment {
            get {
                return ResourceManager.GetString("DdoTypeGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мини-центры.
        /// </summary>
        public static string DdoTypeMiniCenters {
            get {
                return ResourceManager.GetString("DdoTypeMiniCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частные детские сады по гос.дотации.
        /// </summary>
        public static string DdoTypePrivacy {
            get {
                return ResourceManager.GetString("DdoTypePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детские сады поселкового типа.
        /// </summary>
        public static string DdoTypeVillaged {
            get {
                return ResourceManager.GetString("DdoTypeVillaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-сайт детского сада.
        /// </summary>
        public static string DDOWebSite {
            get {
                return ResourceManager.GetString("DDOWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        public static string DecisionReport {
            get {
                return ResourceManager.GetString("DecisionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие c очереди в детскую дошкольную организацию.
        /// </summary>
        public static string DeleteFromDdoQueue {
            get {
                return ResourceManager.GetString("DeleteFromDdoQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГУ «Управление образования города Астаны».
        /// </summary>
        public static string DepartmentOfEducation {
            get {
                return ResourceManager.GetString("DepartmentOfEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать карточку ребенка.
        /// </summary>
        public static string DownloadChildCard {
            get {
                return ResourceManager.GetString("DownloadChildCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронно-цифровая подпись (ЭЦП) заявителя.
        /// </summary>
        public static string ElectronicSignatureOfApplicant {
            get {
                return ResourceManager.GetString("ElectronicSignatureOfApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер направления....
        /// </summary>
        public static string EnterDirectionNumberNulltext {
            get {
                return ResourceManager.GetString("EnterDirectionNumberNulltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер направления....
        /// </summary>
        public static string EnterNumberDirection {
            get {
                return ResourceManager.GetString("EnterNumberDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 минут.
        /// </summary>
        public static string FiveMinuts {
            get {
                return ResourceManager.GetString("FiveMinuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не помню ИИН ребенка.
        /// </summary>
        public static string ForgotIINChild {
            get {
                return ResourceManager.GetString("ForgotIINChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  В предоставлении государственной услуги отказывается по следующим основаниям.
        /// </summary>
        public static string FoundationRenouncement {
            get {
                return ResourceManager.GetString("FoundationRenouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество свободных мест.
        /// </summary>
        public static string FreeCount {
            get {
                return ResourceManager.GetString("FreeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Перейти к базе свободных мест ДДО.
        /// </summary>
        public static string GotoFreePlaceDDO {
            get {
                return ResourceManager.GetString("GotoFreePlaceDDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год группы.
        /// </summary>
        public static string GroupYear {
            get {
                return ResourceManager.GetString("GroupYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В каком случае может быть отказано в предоставлении государственной услуги либо она приостановлена.
        /// </summary>
        public static string HappeningRenouncement {
            get {
                return ResourceManager.GetString("HappeningRenouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о детской дошкольной организации.
        /// </summary>
        public static string InfoChildSchoolOrganizations {
            get {
                return ResourceManager.GetString("InfoChildSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (в очереди с {1}).
        /// </summary>
        public static string InQueueSince {
            get {
                return ResourceManager.GetString("InQueueSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детский сад.
        /// </summary>
        public static string Kindergarten {
            get {
                return ResourceManager.GetString("Kindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык обучения.
        /// </summary>
        public static string LanguageLearning {
            get {
                return ResourceManager.GetString("LanguageLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список доступных дошкольных организаций.
        /// </summary>
        public static string ListSchoolOrganizations {
            get {
                return ResourceManager.GetString("ListSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ручная рассылка уведомлений.
        /// </summary>
        public static string ManualNotice {
            get {
                return ResourceManager.GetString("ManualNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст ребенка: старше 7-ми лет.
        /// </summary>
        public static string MoreSevenAge {
            get {
                return ResourceManager.GetString("MoreSevenAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить выбранный ДДО. Попробуйте еще раз! {0}.
        /// </summary>
        public static string MsgCannotSaveDdo {
            get {
                return ResourceManager.GetString("MsgCannotSaveDdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детский сад должен иметь владельца.
        /// </summary>
        public static string MsgDDOMustHaveOwner {
            get {
                return ResourceManager.GetString("MsgDDOMustHaveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ребенок старше 6 лет не может встать в очередь..
        /// </summary>
        public static string MsgInvalidChildAge {
            get {
                return ResourceManager.GetString("MsgInvalidChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша льгота не подтвердилась. Обратитесь в Управление образования для выяснения причины, либо встаньте в обычную очередь..
        /// </summary>
        public static string MsgPrevilageNotConfirmed {
            get {
                return ResourceManager.GetString("MsgPrevilageNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша очередь была временно заблокирована, так как Вы не выбрали ДДО в течение 5 дней с момента получения уведомления. Для восстановления номера очереди, нажмите кнопку &quot;Подписать и отправить&quot;.
        /// </summary>
        public static string MsgQueueIsLocked {
            get {
                return ResourceManager.GetString("MsgQueueIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный ИИН уже находится в очереди.
        /// </summary>
        public static string MsgXinAlreadyInQueue {
            get {
                return ResourceManager.GetString("MsgXinAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам необходимо в течении 5-ти рабочих дней выбрать из предложенного списка дошкольную организацию.
        /// </summary>
        public static string MustSelectList {
            get {
                return ResourceManager.GetString("MustSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение о постановке на очередь для получения направления в детские дошкольные организации.
        /// </summary>
        public static string NoticeAboutNotice {
            get {
                return ResourceManager.GetString("NoticeAboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон детской дошкольной организации.
        /// </summary>
        public static string PhoneChildSchoolOrganizations {
            get {
                return ResourceManager.GetString("PhoneChildSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка категории льготности.
        /// </summary>
        public static string PrevilageCheck {
            get {
                return ResourceManager.GetString("PrevilageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частные детские сады по гос.дотации.
        /// </summary>
        public static string PrivateKindergartens {
            get {
                return ResourceManager.GetString("PrivateKindergartens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Льготность.
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных льготников.
        /// </summary>
        public static string PrivilegedDatabase {
            get {
                return ResourceManager.GetString("PrivilegedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать частный детский сад по государственному образовательному заказу.
        /// </summary>
        public static string SelectGovermentKindergarten {
            get {
                return ResourceManager.GetString("SelectGovermentKindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор детского сада.
        /// </summary>
        public static string SelectKindergarten {
            get {
                return ResourceManager.GetString("SelectKindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты оказания услуг.
        /// </summary>
        public static string ServiceResult {
            get {
                return ResourceManager.GetString("ServiceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка ребенка в очередь в ДДО.
        /// </summary>
        public static string SetIntoDdoQueue {
            get {
                return ResourceManager.GetString("SetIntoDdoQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка на очередь детей дошкольного возраста.
        /// </summary>
        public static string StagingChildren {
            get {
                return ResourceManager.GetString("StagingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Государственные детские сады.
        /// </summary>
        public static string StateKindergartens {
            get {
                return ResourceManager.GetString("StateKindergartens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по услуге &quot;Постановка на очередь в детские дошкольные организации&quot;.
        /// </summary>
        public static string StatisticsForDdo {
            get {
                return ResourceManager.GetString("StatisticsForDdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снять с очереди.
        /// </summary>
        public static string TakeOfQueue {
            get {
                return ResourceManager.GetString("TakeOfQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название детской дошкольной организации.
        /// </summary>
        public static string TitleSchoolOrganizations {
            get {
                return ResourceManager.GetString("TitleSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string ToSelect {
            get {
                return ResourceManager.GetString("ToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество мест.
        /// </summary>
        public static string TotalNumberCount {
            get {
                return ResourceManager.GetString("TotalNumberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип десткой дошкольной организации.
        /// </summary>
        public static string TypeofChildSchoolOrganizatons {
            get {
                return ResourceManager.GetString("TypeofChildSchoolOrganizatons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать.
        /// </summary>
        public static string UnBlock {
            get {
                return ResourceManager.GetString("UnBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировка.
        /// </summary>
        public static string Unlocking {
            get {
                return ResourceManager.GetString("Unlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варианты выбора ДДО.
        /// </summary>
        public static string VariantOfChoiceDDO {
            get {
                return ResourceManager.GetString("VariantOfChoiceDDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-сайт детской дошкольной организации.
        /// </summary>
        public static string WebsiteSchoolOrganizations {
            get {
                return ResourceManager.GetString("WebsiteSchoolOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год группы.
        /// </summary>
        public static string YearGroup {
            get {
                return ResourceManager.GetString("YearGroup", resourceCulture);
            }
        }
    }
}
