//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Housing2020Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Housing2020Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.Housing2020Resources", typeof(Housing2020Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об объекте.
        /// </summary>
        public static string AboutObject {
            get {
                return ResourceManager.GetString("AboutObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием документов по программе &quot;Жилье 2020&quot;.
        /// </summary>
        public static string AcceptanceOfDocuments {
            get {
                return ResourceManager.GetString("AcceptanceOfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место работы.
        /// </summary>
        public static string EmploymentInfo {
            get {
                return ResourceManager.GetString("EmploymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия свидетельства о рождении детей (до 13 августа 2007 г.).
        /// </summary>
        public static string Housing2020AttBirthDocument {
            get {
                return ResourceManager.GetString("Housing2020AttBirthDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия свидетельства о смерти (до 13 августа 2007 г.).
        /// </summary>
        public static string Housing2020AttDeathDocument {
            get {
                return ResourceManager.GetString("Housing2020AttDeathDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия справки, подтверждающая получение заявителем доходов.
        /// </summary>
        public static string Housing2020AttIncomesDocument {
            get {
                return ResourceManager.GetString("Housing2020AttIncomesDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия свидетельства о заключении (расторжении) брака (до 1 июня 2008 г.).
        /// </summary>
        public static string Housing2020AttMarriageDocument {
            get {
                return ResourceManager.GetString("Housing2020AttMarriageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная копия справки с места работы.
        /// </summary>
        public static string Housing2020AttWorkplaceDocument {
            get {
                return ResourceManager.GetString("Housing2020AttWorkplaceDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники военных действий в демократической республике Афганистан.
        /// </summary>
        public static string Housing2020CatAfgan {
            get {
                return ResourceManager.GetString("Housing2020CatAfgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работники бюджетных организаций.
        /// </summary>
        public static string Housing2020CatBudget {
            get {
                return ResourceManager.GetString("Housing2020CatBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники ликвидации аварий на Чернобыльской атомной станции.
        /// </summary>
        public static string Housing2020CatChernobyl {
            get {
                return ResourceManager.GetString("Housing2020CatChernobyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лица, лишившиеся жилища в результате экологических бедствий.
        /// </summary>
        public static string Housing2020CatEcolog {
            get {
                return ResourceManager.GetString("Housing2020CatEcolog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лица, лишившиеся жилища в результате чрезвычайной ситуации (пожар).
        /// </summary>
        public static string Housing2020CatFire {
            get {
                return ResourceManager.GetString("Housing2020CatFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Государственные служащие.
        /// </summary>
        public static string Housing2020CatGos {
            get {
                return ResourceManager.GetString("Housing2020CatGos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неполная семья.
        /// </summary>
        public static string Housing2020CatIncompFam {
            get {
                return ResourceManager.GetString("Housing2020CatIncompFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семьи, имеющие или воспитывающие детей-инвалидов.
        /// </summary>
        public static string Housing2020CatInvalid {
            get {
                return ResourceManager.GetString("Housing2020CatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многодетная семья.
        /// </summary>
        public static string Housing2020CatLargeFam {
            get {
                return ResourceManager.GetString("Housing2020CatLargeFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военнослужащие.
        /// </summary>
        public static string Housing2020CatMilitary {
            get {
                return ResourceManager.GetString("Housing2020CatMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оралман.
        /// </summary>
        public static string Housing2020CatOralman {
            get {
                return ResourceManager.GetString("Housing2020CatOralman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сирота.
        /// </summary>
        public static string Housing2020CatOrphan {
            get {
                return ResourceManager.GetString("Housing2020CatOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пенсионер.
        /// </summary>
        public static string Housing2020CatPensioner {
            get {
                return ResourceManager.GetString("Housing2020CatPensioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лица, лишившиеся жилища в результате чрезвычайных ситуаций техногенного характера.
        /// </summary>
        public static string Housing2020CatTehnogen {
            get {
                return ResourceManager.GetString("Housing2020CatTehnogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приравненные к УВОВ.
        /// </summary>
        public static string Housing2020CatVov {
            get {
                return ResourceManager.GetString("Housing2020CatVov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МЖК в районе пересечения улиц с проектными наименованиями № 23-31,23-16,23-17,23-30 и А 98, ЛОТ 15.
        /// </summary>
        public static string Housing2020Obj1 {
            get {
                return ResourceManager.GetString("Housing2020Obj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Однокомнатная.
        /// </summary>
        public static string Housing2020OneRoom {
            get {
                return ResourceManager.GetString("Housing2020OneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трехкомнатная.
        /// </summary>
        public static string Housing2020ThreeRooms {
            get {
                return ResourceManager.GetString("Housing2020ThreeRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухкомнатная.
        /// </summary>
        public static string Housing2020TwoRooms {
            get {
                return ResourceManager.GetString("Housing2020TwoRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имеете ли супруга(-у)?.
        /// </summary>
        public static string MarriageStatus {
            get {
                return ResourceManager.GetString("MarriageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша категория не входит в список категорий, которые могут принять участие в данном направлении.
        /// </summary>
        public static string MsgIncorrectCategory {
            get {
                return ResourceManager.GetString("MsgIncorrectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для отправки заявки в архив нажмите кнопку \&quot;Подписать и отправить\&quot;.
        /// </summary>
        public static string MsgSendToArchive {
            get {
                return ResourceManager.GetString("MsgSendToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование списка.
        /// </summary>
        public static string QueueListName {
            get {
                return ResourceManager.GetString("QueueListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер очереди в списке.
        /// </summary>
        public static string QueueListSeqNumber {
            get {
                return ResourceManager.GetString("QueueListSeqNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникальный номер очередника.
        /// </summary>
        public static string QueueSeqNumber {
            get {
                return ResourceManager.GetString("QueueSeqNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор объекта.
        /// </summary>
        public static string RequestedObject {
            get {
                return ResourceManager.GetString("RequestedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество комнат.
        /// </summary>
        public static string RoomsQty {
            get {
                return ResourceManager.GetString("RoomsQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить в архив.
        /// </summary>
        public static string SendToArchive {
            get {
                return ResourceManager.GetString("SendToArchive", resourceCulture);
            }
        }
    }
}
