//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано в привязке права. Право с наименованием: {0} уже привязано к роли {1}.
        /// </summary>
        public static string AdminController_AddRolePermission_RenouncementRight {
            get {
                return ResourceManager.GetString("AdminController_AddRolePermission_RenouncementRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано в регистрации роли. Роль с наименованием: {0} уже существует.
        /// </summary>
        public static string AdminController_CreateNewRole_ExistedRole {
            get {
                return ResourceManager.GetString("AdminController_CreateNewRole_ExistedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование роли не может содержать пробелы.
        /// </summary>
        public static string AdminController_CreateNewRole_WithoutSpace {
            get {
                return ResourceManager.GetString("AdminController_CreateNewRole_WithoutSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка с номером: {0}, была ранее зарегистрирована в системе.
        /// </summary>
        public static string AdminController_ReWorkApplication_ExistedNumber {
            get {
                return ResourceManager.GetString("AdminController_ReWorkApplication_ExistedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано в обновлении роли. Роль с наименованием: {0} не существует.
        /// </summary>
        public static string AdminController_RoleUpdate_ExistedRole {
            get {
                return ResourceManager.GetString("AdminController_RoleUpdate_ExistedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не заполнен шаг заявителя.
        /// </summary>
        public static string ApplicantStepIncomplete {
            get {
                return ResourceManager.GetString("ApplicantStepIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действительно ли вы хотите снять ребенка с очереди? В случае снятия с очереди ребенка, восстановление текущей очереди невозможна.
        /// </summary>
        public static string AreYouSureDequeue {
            get {
                return ResourceManager.GetString("AreYouSureDequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для членов семьи, родившихся до 13 августа 2007 года необходимо прикрепить свидетельство о рождении.
        /// </summary>
        public static string BirthCertRequired {
            get {
                return ResourceManager.GetString("BirthCertRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По ИИН:.
        /// </summary>
        public static string ByXin {
            get {
                return ResourceManager.GetString("ByXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить данные из ГБД ФЛ по ИИН: {0}.
        /// </summary>
        public static string CannotRetrieveInfoFromGBD {
            get {
                return ResourceManager.GetString("CannotRetrieveInfoFromGBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст ребенка не соответствует требованиям услуги.
        /// </summary>
        public static string ChildAgeDoesnMatch {
            get {
                return ResourceManager.GetString("ChildAgeDoesnMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ребенок старше 6 лет не может встать в очередь..
        /// </summary>
        public static string ChildOlderThan6 {
            get {
                return ResourceManager.GetString("ChildOlderThan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {ApplicantName}, сообщаем Вам о завершении оказания государственной услуги по заявлению от.
        /// </summary>
        public static string Completion {
            get {
                return ResourceManager.GetString("Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздел: {0} - обязательный для заполнения.
        /// </summary>
        public static string CompulsoryFilling {
            get {
                return ResourceManager.GetString("CompulsoryFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалите все дублирующиеся элементы из списка..
        /// </summary>
        public static string DeleteDublicate {
            get {
                return ResourceManager.GetString("DeleteDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенный уникальный номер не соответствует данным заявителя. Пожалуйста, убедитесь в правильности введенной информации.
        /// </summary>
        public static string DoesntMatch {
            get {
                return ResourceManager.GetString("DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронный адрес не указан..
        /// </summary>
        public static string EmailIsNotSpecified {
            get {
                return ResourceManager.GetString("EmailIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при добавлении свидетельства о рождении.
        /// </summary>
        public static string ErrorAddingBirthSertificate {
            get {
                return ResourceManager.GetString("ErrorAddingBirthSertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздел: {0}. файл: {1} - не прошел проверку.
        /// </summary>
        public static string FileFailedValidation {
            get {
                return ResourceManager.GetString("FileFailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поля корректно.
        /// </summary>
        public static string FillFeildCorrect {
            get {
                return ResourceManager.GetString("FillFeildCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя содержит не допустимые символы.
        /// </summary>
        public static string FirstNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("FirstNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование ГУ.
        /// </summary>
        public static string GovermenrtOrganizationName {
            get {
                return ResourceManager.GetString("GovermenrtOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН не заполнен!.
        /// </summary>
        public static string IinNotFilled {
            get {
                return ResourceManager.GetString("IinNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется поле ИИН заявителя..
        /// </summary>
        public static string IinRequired {
            get {
                return ResourceManager.GetString("IinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН должен состоять из 12 цифр.
        /// </summary>
        public static string IinShouldConsistOf12Digits {
            get {
                return ResourceManager.GetString("IinShouldConsistOf12Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно  заполнено поле.
        /// </summary>
        public static string IncorrectFieldFormat {
            get {
                return ResourceManager.GetString("IncorrectFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По данным ГБД ЗАГС у вас зарегистрирован брак, не указанный при заполнении заявки.
        /// </summary>
        public static string IncorrectMarriageStatus {
            get {
                return ResourceManager.GetString("IncorrectMarriageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {ApplicantName}, сообщаем, что Ваше заявление от &quot; +
        ///            $&quot;{RegistrationDateTime.ToString(&quot;dd.MM.yyyy&quot;)} [{RegistrationDateTime.ToString(&quot;HH:mm&quot;)}] №{RequestNumber} &quot; +
        ///            $&quot;на услугу \&quot;{Service.GetDisplayName()}\&quot; принято в работу со следующим списком приложенных документов:.
        /// </summary>
        public static string ItIsTakenIntoOperation {
            get {
                return ResourceManager.GetString("ItIsTakenIntoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия содержит не допустимые символы.
        /// </summary>
        public static string LastNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("LastNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для браков зарегистрированных до 1 июня 2008 года необходимо прикрепить свидетельство о браке.
        /// </summary>
        public static string MarriageCertRequired {
            get {
                return ResourceManager.GetString("MarriageCertRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая),    Уведомляем Вас о том, что подошла очередь на получение направления в детскую дошкольную организацию по заявлению № Необходимо в течение 3-х дней выбрать один из доступных детских дошкольных организации(ДДО) в личном кабинете (http://ises.astana.kz/), либо обратиться в Управление образования акимата города Астана.  Очередь в детский сад.
        /// </summary>
        public static string MessageToApplicant {
            get {
                return ResourceManager.GetString("MessageToApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(-ая),    в Вашу детскую дошкольную организацию получил(а) направление Оповещение о выдаче направляения в ваше ДДО.
        /// </summary>
        public static string MessageToDirector {
            get {
                return ResourceManager.GetString("MessageToDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество содержит не допустимые символы.
        /// </summary>
        public static string MiddleNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("MiddleNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно.
        /// </summary>
        public static string Necessarily {
            get {
                return ResourceManager.GetString("Necessarily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны выбрать язык.
        /// </summary>
        public static string NeedToChooseLang {
            get {
                return ResourceManager.GetString("NeedToChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет приложенных документов.
        /// </summary>
        public static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для подписи.
        /// </summary>
        public static string NotDataSignature {
            get {
                return ResourceManager.GetString("NotDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ничего не найдено!.
        /// </summary>
        public static string NotFind {
            get {
                return ResourceManager.GetString("NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст ребенка не должен превышать 6 лет.
        /// </summary>
        public static string NotMoreSixAge {
            get {
                return ResourceManager.GetString("NotMoreSixAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить сообщение.
        /// </summary>
        public static string NotSent {
            get {
                return ResourceManager.GetString("NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные пароли не совпадают.
        /// </summary>
        public static string PasswordConfirmationNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль {0} должен содержать не менее {1} символов..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном направлении могут принять участие граждане, имеющие постоянную регистрацию по месту жительства в г.Астана..
        /// </summary>
        public static string PermanentRegistration {
            get {
                return ResourceManager.GetString("PermanentRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона не указан..
        /// </summary>
        public static string PhoneNumberIsNotSpecified {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} уведомляем Вас о том, что Вам отказано в выдаче справки по опеке и попечительству над {1} {2} года рождения и над его (ее) имуществом.
        /// </summary>
        public static string RefusedACertificateOfGuardianship {
            get {
                return ResourceManager.GetString("RefusedACertificateOfGuardianship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {ApplicantName}, уведомляем Вас о том, что ваше заявление на услугу \&quot;{Service.GetDisplayName()}\&quot; &quot; +
        ///                $&quot;зарегистрировано от {RegistrationDateTime.ToString(&quot;dd.MM.yyyy&quot;)} [{RegistrationDateTime.ToString(&quot;HH:mm&quot;)}] № {RequestNumber}&quot;+ 
        ///                $&quot; ({RequestedObject.GetDisplayName()}, {Rooms.GetDisplayName()}, площадь: {Area}).
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании услуги «Назначение выплаты пособия опекунам или попечителям на содержание ребенка-сироты (детей-сирот) и ребенка (детей), оставшегося без попечения родителей» по заявлению от.
        /// </summary>
        public static string Renouncement {
            get {
                return ResourceManager.GetString("Renouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании государственной услуги «Установление опеки или попечительства над ребенком-сиротой (детьми-сиротами) и ребенком (детьми), оставшимися без попечения родителей» от {1} под № {2}.
        /// </summary>
        public static string RenouncementCustody {
            get {
                return ResourceManager.GetString("RenouncementCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании услуги «Выдача архивных справок» по заявлению от.
        /// </summary>
        public static string RenouncementReferences {
            get {
                return ResourceManager.GetString("RenouncementReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) заявитель, на Ваше имя в системе уже зарегистрировано заявление.
        /// </summary>
        public static string RequestAlreadyExists {
            get {
                return ResourceManager.GetString("RequestAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поле.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите значение.
        /// </summary>
        public static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные ЭЦП, отличаются от данных заявителя. Просим подписать заявление с помощью следующей ЭЦП: {0}.
        /// </summary>
        public static string SignatureOwnerMismatch {
            get {
                return ResourceManager.GetString("SignatureOwnerMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписанные данные не прошли валидацию.
        /// </summary>
        public static string SignedValidationFailed {
            get {
                return ResourceManager.GetString("SignedValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо подписать данные перед регистрацией.
        /// </summary>
        public static string SignRequired {
            get {
                return ResourceManager.GetString("SignRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные ЭЦП, отличаются от данных заявителя. Просим подписать заявление с помощью ЭЦП заявителя: {0}.
        /// </summary>
        public static string SignWithApplicantEcp {
            get {
                return ResourceManager.GetString("SignWithApplicantEcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено допустимое число символов.
        /// </summary>
        public static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Базе данных опекунов (попечителей)  по городу Астана Вы не значитесь.
        /// </summary>
        public static string TheDatabaseGuardiansInHheCityOfAstanaYouDoNotMean {
            get {
                return ResourceManager.GetString("TheDatabaseGuardiansInHheCityOfAstanaYouDoNotMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string ThePasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ThePasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящая справка выдана гр.(ке): {0} проживающему(ей) в &quot; +
        ///                                     &quot;{1} в том, что он(она) &quot; +
        ///                                     &quot;согласно решению акима (город, район) №{2} от {3} действительно назначен(а) опекуном над.
        /// </summary>
        public static string ThisCertificateWillBeIssued {
            get {
                return ResourceManager.GetString("ThisCertificateWillBeIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители, стоящие в очереди могут прослеживать продвижение очереди через порталы электронных услуг (http://e.astana.kz,http://e.gov.kz), а так же позвонить в Контакт-центр акимата города Астаны по номеру телефону 55-66-55&quot; 
        /////                        + &quot; В случае несогласия с полученым решением, Вам предоставляется возможность обжаловать данное решение до &quot;.
        /// </summary>
        public static string TraceAdvancement {
            get {
                return ResourceManager.GetString("TraceAdvancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректную дату.
        /// </summary>
        public static string WriteCorrectDate {
            get {
                return ResourceManager.GetString("WriteCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный номер.
        /// </summary>
        public static string WriteCorrectNumber {
            get {
                return ResourceManager.GetString("WriteCorrectNumber", resourceCulture);
            }
        }
    }
}
