//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.NameResources", typeof(NameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № лицевого счета.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата акимата.
        /// </summary>
        public static string AkimaDateTime {
            get {
                return ResourceManager.GetString("AkimaDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер акимата.
        /// </summary>
        public static string AkimatsNumber {
            get {
                return ResourceManager.GetString("AkimatsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата назначения.
        /// </summary>
        public static string AllowanceAppointmentDate {
            get {
                return ResourceManager.GetString("AllowanceAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string AllowanceSum {
            get {
                return ResourceManager.GetString("AllowanceSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения заявителя.
        /// </summary>
        public static string ApplicantBirthDate {
            get {
                return ResourceManager.GetString("ApplicantBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О заявителя.
        /// </summary>
        public static string ApplicantFullName {
            get {
                return ResourceManager.GetString("ApplicantFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН заявителя.
        /// </summary>
        public static string ApplicantIin {
            get {
                return ResourceManager.GetString("ApplicantIin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о заявителе.
        /// </summary>
        public static string ApplicantInfo {
            get {
                return ResourceManager.GetString("ApplicantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод информации о заявителе.
        /// </summary>
        public static string ApplicantInformation {
            get {
                return ResourceManager.GetString("ApplicantInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия заявителя.
        /// </summary>
        public static string ApplicantLastName {
            get {
                return ResourceManager.GetString("ApplicantLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество заявителя.
        /// </summary>
        public static string ApplicantMiddleName {
            get {
                return ResourceManager.GetString("ApplicantMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя заявителя.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессия заявителя.
        /// </summary>
        public static string ApplicantOccupation {
            get {
                return ResourceManager.GetString("ApplicantOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Род отношений заявителя с несовершеннолетним.
        /// </summary>
        public static string ApplicantRelationsWithFoster {
            get {
                return ResourceManager.GetString("ApplicantRelationsWithFoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление услугополучателя.
        /// </summary>
        public static string ApplicantRequest {
            get {
                return ResourceManager.GetString("ApplicantRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер зарплаты.
        /// </summary>
        public static string ApproximateSalary {
            get {
                return ResourceManager.GetString("ApproximateSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивная справка.
        /// </summary>
        public static string ArchiveTranscript {
            get {
                return ResourceManager.GetString("ArchiveTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование вложения.
        /// </summary>
        public static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложения.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование банка.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание.
        /// </summary>
        public static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания/изменения.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создал/изменил.
        /// </summary>
        public static string ChangedUser {
            get {
                return ResourceManager.GetString("ChangedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История изменений.
        /// </summary>
        public static string ChangeHistory {
            get {
                return ResourceManager.GetString("ChangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО Акима района(города).
        /// </summary>
        public static string ChiefFullName {
            get {
                return ResourceManager.GetString("ChiefFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения ребенка.
        /// </summary>
        public static string ChildBirthDate {
            get {
                return ResourceManager.GetString("ChildBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка ребенка.
        /// </summary>
        public static string Childcard {
            get {
                return ResourceManager.GetString("Childcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № свидетельства о рождении.
        /// </summary>
        public static string ChildDocumentNumber {
            get {
                return ResourceManager.GetString("ChildDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя ребенка.
        /// </summary>
        public static string ChildFirstName {
            get {
                return ResourceManager.GetString("ChildFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО ребенка.
        /// </summary>
        public static string ChildFullName {
            get {
                return ResourceManager.GetString("ChildFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН ребенка.
        /// </summary>
        public static string ChildIin {
            get {
                return ResourceManager.GetString("ChildIin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о ребенке.
        /// </summary>
        public static string ChildInfo {
            get {
                return ResourceManager.GetString("ChildInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод информации о ребенке.
        /// </summary>
        public static string ChildInformation {
            get {
                return ResourceManager.GetString("ChildInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия ребенка.
        /// </summary>
        public static string ChildLastName {
            get {
                return ResourceManager.GetString("ChildLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество ребенка.
        /// </summary>
        public static string ChildMiddleName {
            get {
                return ResourceManager.GetString("ChildMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение нового пароля.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер ЦОН.
        /// </summary>
        public static string ConNumber {
            get {
                return ResourceManager.GetString("ConNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название курса.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        public static string CreationDateTime {
            get {
                return ResourceManager.GetString("CreationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее состояние.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № постановления об опеке.
        /// </summary>
        public static string CustodyOrderNumber {
            get {
                return ResourceManager.GetString("CustodyOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата решения.
        /// </summary>
        public static string DateOfDecision {
            get {
                return ResourceManager.GetString("DateOfDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановления об опеке.
        /// </summary>
        public static string DateOfDecisionOnCustody {
            get {
                return ResourceManager.GetString("DateOfDecisionOnCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановления.
        /// </summary>
        public static string DateOfResolution {
            get {
                return ResourceManager.GetString("DateOfResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата отказа.
        /// </summary>
        public static string DateRenouncement {
            get {
                return ResourceManager.GetString("DateRenouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата свидетельства о смерти.
        /// </summary>
        public static string DeathCertificateDate {
            get {
                return ResourceManager.GetString("DeathCertificateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № свидетельства о смерти.
        /// </summary>
        public static string DeathCertificateNumber {
            get {
                return ResourceManager.GetString("DeathCertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер решения.
        /// </summary>
        public static string DecisionNumber {
            get {
                return ResourceManager.GetString("DecisionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № постановления.
        /// </summary>
        public static string DecreeNumber {
            get {
                return ResourceManager.GetString("DecreeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Департамент.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление образования.
        /// </summary>
        public static string DepartmentOfEducation {
            get {
                return ResourceManager.GetString("DepartmentOfEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string DesiredPosition {
            get {
                return ResourceManager.GetString("DesiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи направления.
        /// </summary>
        public static string DirectionDate {
            get {
                return ResourceManager.GetString("DirectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер дела.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите наименование медицинского препарата.
        /// </summary>
        public static string EnterMedName {
            get {
                return ResourceManager.GetString("EnterMedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная услуга.
        /// </summary>
        public static string eService {
            get {
                return ResourceManager.GetString("eService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Услуги.
        /// </summary>
        public static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя члена семьи.
        /// </summary>
        public static string FamilyMemberFirstName {
            get {
                return ResourceManager.GetString("FamilyMemberFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО члена семьи.
        /// </summary>
        public static string FamilyMemberFullName {
            get {
                return ResourceManager.GetString("FamilyMemberFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия члена семьи.
        /// </summary>
        public static string FamilyMemberLastName {
            get {
                return ResourceManager.GetString("FamilyMemberLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество члена семьи.
        /// </summary>
        public static string FamilyMemberMiddleName {
            get {
                return ResourceManager.GetString("FamilyMemberMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество членов семьи.
        /// </summary>
        public static string FamilyMembersQty {
            get {
                return ResourceManager.GetString("FamilyMembersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название файла.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файлов.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уход за несовершеннолетним.
        /// </summary>
        public static string FosterCare {
            get {
                return ResourceManager.GetString("FosterCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О..
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы с ГБД.
        /// </summary>
        public static string GBDdocuments {
            get {
                return ResourceManager.GetString("GBDdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем выдано.
        /// </summary>
        public static string IDIssued {
            get {
                return ResourceManager.GetString("IDIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        public static string IDIssuedDate {
            get {
                return ResourceManager.GetString("IDIssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № удостоверения личности.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН.
        /// </summary>
        public static string IIN {
            get {
                return ResourceManager.GetString("IIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящая дата Акимата.
        /// </summary>
        public static string IncomingAkimatDate {
            get {
                return ResourceManager.GetString("IncomingAkimatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящий номер Акимата.
        /// </summary>
        public static string IncomingAkimatNumber {
            get {
                return ResourceManager.GetString("IncomingAkimatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год свидетельства о наследстве.
        /// </summary>
        public static string InheritanceCertificateYear {
            get {
                return ResourceManager.GetString("InheritanceCertificateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод дополнительной информации.
        /// </summary>
        public static string InputDetailedInformation {
            get {
                return ResourceManager.GetString("InputDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родственные отношения с наследодателем.
        /// </summary>
        public static string Kinship {
            get {
                return ResourceManager.GetString("Kinship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время последнего изменения.
        /// </summary>
        public static string LastChangeDate {
            get {
                return ResourceManager.GetString("LastChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее изменения.
        /// </summary>
        public static string LastStateDateTime {
            get {
                return ResourceManager.GetString("LastStateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем выдана лицензия.
        /// </summary>
        public static string LicenseIssueOffice {
            get {
                return ResourceManager.GetString("LicenseIssueOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год лицензии.
        /// </summary>
        public static string LicenseYear {
            get {
                return ResourceManager.GetString("LicenseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семейное положение.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заключения брака.
        /// </summary>
        public static string MarriageDate {
            get {
                return ResourceManager.GetString("MarriageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивированный отказ.
        /// </summary>
        public static string MotivatedRefuse {
            get {
                return ResourceManager.GetString("MotivatedRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название учебного заведения.
        /// </summary>
        public static string NameOfSchool {
            get {
                return ResourceManager.GetString("NameOfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национальность.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о регистрации заявления.
        /// </summary>
        public static string NoticeOfApplicationForRegistration {
            get {
                return ResourceManager.GetString("NoticeOfApplicationForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение  о приеме документов на оказание услуги.
        /// </summary>
        public static string NotificationOfAcceptanceOfDocuments {
            get {
                return ResourceManager.GetString("NotificationOfAcceptanceOfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер постановления.
        /// </summary>
        public static string NumberOfResolution {
            get {
                return ResourceManager.GetString("NumberOfResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № свидетельства о рождении.
        /// </summary>
        public static string NumberOftheBirthCertificate {
            get {
                return ResourceManager.GetString("NumberOftheBirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование органа.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выходные документы.
        /// </summary>
        public static string OutputDocuments {
            get {
                return ResourceManager.GetString("OutputDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН родителя.
        /// </summary>
        public static string ParentIIN {
            get {
                return ResourceManager.GetString("ParentIIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период выплаты пособия.
        /// </summary>
        public static string PaymentPeriod {
            get {
                return ResourceManager.GetString("PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пенсионный фонд.
        /// </summary>
        public static string PensionFund {
            get {
                return ResourceManager.GetString("PensionFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер ПЭП.
        /// </summary>
        public static string PepNumber {
            get {
                return ResourceManager.GetString("PepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип лица.
        /// </summary>
        public static string PersonType {
            get {
                return ResourceManager.GetString("PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите значение.
        /// </summary>
        public static string PickValue {
            get {
                return ResourceManager.GetString("PickValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтовый адрес.
        /// </summary>
        public static string PostalAddress {
            get {
                return ResourceManager.GetString("PostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детская дошкольная организация.
        /// </summary>
        public static string PreschoolOorganization {
            get {
                return ResourceManager.GetString("PreschoolOorganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория льготности.
        /// </summary>
        public static string PrivilageCategory {
            get {
                return ResourceManager.GetString("PrivilageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип льготности.
        /// </summary>
        public static string PrivilageType {
            get {
                return ResourceManager.GetString("PrivilageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип льготника.
        /// </summary>
        public static string PrivilageTypeName {
            get {
                return ResourceManager.GetString("PrivilageTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сфера деятельности.
        /// </summary>
        public static string ProfessionalArea {
            get {
                return ResourceManager.GetString("ProfessionalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановки в очередь.
        /// </summary>
        public static string QueueDateTime {
            get {
                return ResourceManager.GetString("QueueDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер очереди.
        /// </summary>
        public static string QueueNumber {
            get {
                return ResourceManager.GetString("QueueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановки.
        /// </summary>
        public static string QueueRegistrationDate {
            get {
                return ResourceManager.GetString("QueueRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание оформления опеки и попечительства.
        /// </summary>
        public static string ReasonOfGuardianship {
            get {
                return ResourceManager.GetString("ReasonOfGuardianship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о приеме.
        /// </summary>
        public static string ReceptionInfo {
            get {
                return ResourceManager.GetString("ReceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время приема.
        /// </summary>
        public static string ReceptionTime {
            get {
                return ResourceManager.GetString("ReceptionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подкатегория.
        /// </summary>
        public static string RefCitizensSubCategory {
            get {
                return ResourceManager.GetString("RefCitizensSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родственные отношения.
        /// </summary>
        public static string RefFamilyRelationship {
            get {
                return ResourceManager.GetString("RefFamilyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Род занятий.
        /// </summary>
        public static string RefOccupation {
            get {
                return ResourceManager.GetString("RefOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степень родства.
        /// </summary>
        public static string RefRelationDegree {
            get {
                return ResourceManager.GetString("RefRelationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Социальный статус.
        /// </summary>
        public static string RefSocialStatus {
            get {
                return ResourceManager.GetString("RefSocialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № тех. паспорта.
        /// </summary>
        public static string RegNumber {
            get {
                return ResourceManager.GetString("RegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи тех. паспорта.
        /// </summary>
        public static string RegNumberDate {
            get {
                return ResourceManager.GetString("RegNumberDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина отказа.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родственная связь.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессия.
        /// </summary>
        public static string RelativeOccupation {
            get {
                return ResourceManager.GetString("RelativeOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить этот браузер?.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина снятия.
        /// </summary>
        public static string RemoveReason {
            get {
                return ResourceManager.GetString("RemoveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием заявления.
        /// </summary>
        public static string RequestAcceptance {
            get {
                return ResourceManager.GetString("RequestAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время регистрации.
        /// </summary>
        public static string RequestDateTime {
            get {
                return ResourceManager.GetString("RequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальная информация по заявке.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о заявлении.
        /// </summary>
        public static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод информации о заявке.
        /// </summary>
        public static string RequestInformation {
            get {
                return ResourceManager.GetString("RequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № заявки.
        /// </summary>
        public static string RequestNum {
            get {
                return ResourceManager.GetString("RequestNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер заявления.
        /// </summary>
        public static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период по.
        /// </summary>
        public static string RequestPeriodEnds {
            get {
                return ResourceManager.GetString("RequestPeriodEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период с.
        /// </summary>
        public static string RequestPeriodStarts {
            get {
                return ResourceManager.GetString("RequestPeriodStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель запроса.
        /// </summary>
        public static string RequestPurpose {
            get {
                return ResourceManager.GetString("RequestPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип заявки.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид запрашиваемой услуги.
        /// </summary>
        public static string RequestTypeOfService {
            get {
                return ResourceManager.GetString("RequestTypeOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли пользователя.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий график.
        /// </summary>
        public static string ScheduleWork {
            get {
                return ResourceManager.GetString("ScheduleWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуга.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принятие решения по услуге.
        /// </summary>
        public static string ServiceDecision {
            get {
                return ResourceManager.GetString("ServiceDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ по услуге.
        /// </summary>
        public static string ServiceFailure {
            get {
                return ResourceManager.GetString("ServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата с.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСУДАРСТВЕННЫЙ АРХИВ.
        /// </summary>
        public static string STATEARCHIVES {
            get {
                return ResourceManager.GetString("STATEARCHIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановки в очередь.
        /// </summary>
        public static string StateInQueueDateTime {
            get {
                return ResourceManager.GetString("StateInQueueDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Государственный номер.
        /// </summary>
        public static string StateNumber {
            get {
                return ResourceManager.GetString("StateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГУ \&quot;Управление образования г.Астаны.
        /// </summary>
        public static string TheStatementOfWithdrawalFromHheQueue {
            get {
                return ResourceManager.GetString("TheStatementOfWithdrawalFromHheQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип учетной записи.
        /// </summary>
        public static string TypeOfAccount {
            get {
                return ResourceManager.GetString("TypeOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указан.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт работы.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный адрес электронной почты.
        /// </summary>
        public static string WriteCorrectEmail {
            get {
                return ResourceManager.GetString("WriteCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный номер телефона.
        /// </summary>
        public static string WriteCorrectPhoneNumber {
            get {
                return ResourceManager.GetString("WriteCorrectPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год выпуска.
        /// </summary>
        public static string YearOfIssue {
            get {
                return ResourceManager.GetString("YearOfIssue", resourceCulture);
            }
        }
    }
}
