//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueueToLandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueueToLandResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.QueueToLandResources", typeof(QueueToLandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных заявления на постановку в очередь на жилье.
        /// </summary>
        public static string EditQueueStep {
            get {
                return ResourceManager.GetString("EditQueueStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о получении земельного участка.
        /// </summary>
        public static string LandRequizitionInfo {
            get {
                return ResourceManager.GetString("LandRequizitionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставить в очередь.
        /// </summary>
        public static string QueueLandConfirmTask {
            get {
                return ResourceManager.GetString("QueueLandConfirmTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать.
        /// </summary>
        public static string QueueLandRefuseTask {
            get {
                return ResourceManager.GetString("QueueLandRefuseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача мотивированного отказа.
        /// </summary>
        public static string QueueToLandRejectStep {
            get {
                return ResourceManager.GetString("QueueToLandRejectStep", resourceCulture);
            }
        }
    }
}
