//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.ReportTypeResources", typeof(ReportTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение о назначении пособия опекуну или попечителю.
        /// </summary>
        public static string AllowancePaymentsMatchingInstall {
            get {
                return ResourceManager.GetString("AllowancePaymentsMatchingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свидетельство о рождении.
        /// </summary>
        public static string CertificateOfBirth {
            get {
                return ResourceManager.GetString("CertificateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свидетельство о заключении брака.
        /// </summary>
        public static string CertificateOfMarriage {
            get {
                return ResourceManager.GetString("CertificateOfMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием граждан. Перенос приема.
        /// </summary>
        public static string CitizensReseptionDateTransferedRepor {
            get {
                return ResourceManager.GetString("CitizensReseptionDateTransferedRepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием граждан. Запись на прием.
        /// </summary>
        public static string CitizensReseptionRecordedReport {
            get {
                return ResourceManager.GetString("CitizensReseptionRecordedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием граждан. Отклонение заявления.
        /// </summary>
        public static string CitizensReseptioRejectedReport {
            get {
                return ResourceManager.GetString("CitizensReseptioRejectedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление в мини-центры.
        /// </summary>
        public static string DayCareMiniCenterDecisionReport {
            get {
                return ResourceManager.GetString("DayCareMiniCenterDecisionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка ребёнка.
        /// </summary>
        public static string DayCareQueueChildcard {
            get {
                return ResourceManager.GetString("DayCareQueueChildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление в ДДО.
        /// </summary>
        public static string DayCareQueueDecisionReport {
            get {
                return ResourceManager.GetString("DayCareQueueDecisionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление в частный ДДО.
        /// </summary>
        public static string DayCareQueuePrivateDecisionReport {
            get {
                return ResourceManager.GetString("DayCareQueuePrivateDecisionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация ребенка в книге учета.
        /// </summary>
        public static string DayCareQueueRegistrated {
            get {
                return ResourceManager.GetString("DayCareQueueRegistrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение о снятии с очереди.
        /// </summary>
        public static string DayCareQueueRemovalNotification {
            get {
                return ResourceManager.GetString("DayCareQueueRemovalNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление о снятии с очереди.
        /// </summary>
        public static string DayCareQueueRemovalReport {
            get {
                return ResourceManager.GetString("DayCareQueueRemovalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление в детский сад поселкового типа.
        /// </summary>
        public static string DayCareQueueVilagedDecisionReport {
            get {
                return ResourceManager.GetString("DayCareQueueVilagedDecisionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об отказе.
        /// </summary>
        public static string DenyNotification {
            get {
                return ResourceManager.GetString("DenyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение о приеме документов.
        /// </summary>
        public static string DocumentReceptionReport {
            get {
                return ResourceManager.GetString("DocumentReceptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об ошибке.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по Жилью2020.
        /// </summary>
        public static string Housing2020Report {
            get {
                return ResourceManager.GetString("Housing2020Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о пенсионных начислениях.
        /// </summary>
        public static string PensionPaymentsCertificate {
            get {
                return ResourceManager.GetString("PensionPaymentsCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивированный отказ.
        /// </summary>
        public static string QueueToTheLandRefused {
            get {
                return ResourceManager.GetString("QueueToTheLandRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка в очередь.
        /// </summary>
        public static string QueueToTheLandStateInQueue {
            get {
                return ResourceManager.GetString("QueueToTheLandStateInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка об отсутствии (наличии) недвижимости.
        /// </summary>
        public static string RealEstateCertificate {
            get {
                return ResourceManager.GetString("RealEstateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о регистрации.
        /// </summary>
        public static string RegistrationReport {
            get {
                return ResourceManager.GetString("RegistrationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка заявки.
        /// </summary>
        public static string RequestSummary {
            get {
                return ResourceManager.GetString("RequestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение о завершении оказания услуги.
        /// </summary>
        public static string ServiceCompletionReport {
            get {
                return ResourceManager.GetString("ServiceCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача справок по опеке и попечительству.
        /// </summary>
        public static string TrusteeshipCertificatesIssueConfirm {
            get {
                return ResourceManager.GetString("TrusteeshipCertificatesIssueConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановление акима.
        /// </summary>
        public static string TrusteeshipMatchingInstall {
            get {
                return ResourceManager.GetString("TrusteeshipMatchingInstall", resourceCulture);
            }
        }
    }
}
