//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании услуги «Назначение выплаты пособия опекунам или попечителям на содержание ребенка-сироты (детей-сирот) и ребенка (детей), оставшегося без попечения родителей» по заявлению от {1} № {2} .
        /// </summary>
        public static string AllowancePaymentsRefuseNotification_Text {
            get {
                return ResourceManager.GetString("AllowancePaymentsRefuseNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Услуги.
        /// </summary>
        public static string ArchiveTranscriptDenyNotificationModel_ExecutorUserName {
            get {
                return ResourceManager.GetString("ArchiveTranscriptDenyNotificationModel_ExecutorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина отказа: {0}.
        /// </summary>
        public static string ArchiveTranscriptDenyNotificationModel_Reason {
            get {
                return ResourceManager.GetString("ArchiveTranscriptDenyNotificationModel_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании услуги «Выдача архивных справок» по заявлению от {1} № {2}..
        /// </summary>
        public static string ArchiveTranscriptDenyNotificationModel_Text {
            get {
                return ResourceManager.GetString("ArchiveTranscriptDenyNotificationModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(-ая) {0}, по Вашеу заявлению  
        ///с № {1} назначеный Вам  прием к {2} 
        ///{3} был перенесен на Дату  {4}
        ///Время: {5} 
        ///Данные ведущего прием: {6}.
        /// </summary>
        public static string CitizensReceptionDateTransferedReport_NotificationBody {
            get {
                return ResourceManager.GetString("CitizensReceptionDateTransferedReport_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление 
        /// о Перенос приема по вашему заявлению.
        /// </summary>
        public static string CitizensReceptionDateTransferedReport_NotificationHeader {
            get {
                return ResourceManager.GetString("CitizensReceptionDateTransferedReport_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(-ая) {0}, уведомляем вас о том, 
        ///что по вашему заявлению с №{1} назначен прием 
        ///к: {2}
        ///Данные ведущего прием:{2}
        ///{3} 
        ///На дату: {4}
        ///Время: {5} .
        /// </summary>
        public static string CitizensReceptionRecordedReport_NotificationBody {
            get {
                return ResourceManager.GetString("CitizensReceptionRecordedReport_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о записи на прием.
        /// </summary>
        public static string CitizensReceptionRecordedReport_NotificationHeader {
            get {
                return ResourceManager.GetString("CitizensReceptionRecordedReport_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об отклонение заявления.
        /// </summary>
        public static string CitizensReceptionRejectedReport_Fill_NotificationHeader {
            get {
                return ResourceManager.GetString("CitizensReceptionRejectedReport_Fill_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(-ая) {0}, по вашему заявленю 
        ///с № {1}к {2} {3}
        ///отклонено по слудющей причине: 
        ///{4} 
        ///Данные ведущего прием: {5}.
        /// </summary>
        public static string CitizensReceptionRejectedReport_NotificationBody {
            get {
                return ResourceManager.GetString("CitizensReceptionRejectedReport_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об отклонении заявления.
        /// </summary>
        public static string CitizensReceptionRejectedReport_NotificationHeader {
            get {
                return ResourceManager.GetString("CitizensReceptionRejectedReport_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГУ &quot;Управление образования г.Алматы&quot;.
        /// </summary>
        public static string CompletionNotification_ExecutorName {
            get {
                return ResourceManager.GetString("CompletionNotification_ExecutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение 
        /// о завершении оказания услуги &quot;{0}&quot;.
        /// </summary>
        public static string CompletionNotification_HeaderText {
            get {
                return ResourceManager.GetString("CompletionNotification_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0}, сообщаем Вам о завершении оказания государственной услуги &quot;{1}&quot; по заявлению от {2} [{3}] №{4}..
        /// </summary>
        public static string CompletionNotification_NotificationText {
            get {
                return ResourceManager.GetString("CompletionNotification_NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Направление в государственную детскую 
        ///дошкольную организацию № {0}.
        /// </summary>
        public static string DayCareQueueDecisionModel_NotificationHeader {
            get {
                return ResourceManager.GetString("DayCareQueueDecisionModel_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление в мини-центр № {0}.
        /// </summary>
        public static string DayCareQueueMinicenterDecisionModel_NotificationHeader {
            get {
                return ResourceManager.GetString("DayCareQueueMinicenterDecisionModel_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Направление в частный детский сад 
        /// по государственному образовательному заказу № {0}.
        /// </summary>
        public static string DayCareQueuePrivateDecisionModel_NotificationHeader {
            get {
                return ResourceManager.GetString("DayCareQueuePrivateDecisionModel_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      {0}, {1} года рождения, зарегистрирован(а) в &quot;Книге учета будущих воспитанников государственного детского учреждения&quot;от {2} под № {3}..
        /// </summary>
        public static string DayCareQueueRegistratedModel_NotificationBody {
            get {
                return ResourceManager.GetString("DayCareQueueRegistratedModel_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение о регистрации ребенка в книге учета будущих воспитанников государственного детского учреждения.
        /// </summary>
        public static string DayCareQueueRegistratedModel_NotificationHeader {
            get {
                return ResourceManager.GetString("DayCareQueueRegistratedModel_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Прошу Вас снять с очереди по государственной услуге &quot;Постановка на очередь детей дошкольного возраста (до 7 лет) для направления в детские дошкольные организации&quot; моего ребенка {0}.
        /// Причина: {1}..
        /// </summary>
        public static string DayCareQueueRemovalModel_NotificationBody {
            get {
                return ResourceManager.GetString("DayCareQueueRemovalModel_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление.
        /// </summary>
        public static string DayCareQueueRemovalModel_NotificationHeader {
            get {
                return ResourceManager.GetString("DayCareQueueRemovalModel_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая), {0} по заявлению №{1} ребенок {2} был снят с очереди по причине достижения 7-ми летнего возраста..
        /// </summary>
        public static string DayCareQueueRemovalNotificationText {
            get {
                return ResourceManager.GetString("DayCareQueueRemovalNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем Вам о прекращении опеки или попечительства над {1} от {2} по причине: {3}..
        /// </summary>
        public static string EtrusteeshipCompleteNotification_Text {
            get {
                return ResourceManager.GetString("EtrusteeshipCompleteNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о регистрации заявления.
        /// </summary>
        public static string Housing2020RegistrationNotification_HeaderText {
            get {
                return ResourceManager.GetString("Housing2020RegistrationNotification_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0}, уведомляем Вас о том, что ваше заявление на услугу &quot;{1}&quot; зарегистрировано от {2} [{3}] № {4} ({5}, {6}, площадь: {7})..
        /// </summary>
        public static string Housing2020RegistrationNotification_NotificationText {
            get {
                return ResourceManager.GetString("Housing2020RegistrationNotification_NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0}, сообщаем, что Вам отказано в  оказании государственной услуги «Постановка в очередь для получения земельного участка под индивидуальное жилищное строительство» по заявлению от {1} №{2}.
        /// </summary>
        public static string QueueToTheLandRefusedReport_NotificationBody {
            get {
                return ResourceManager.GetString("QueueToTheLandRefusedReport_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УВЕДОМЛЕНИЕ ОБ ОТКАЗЕ.
        /// </summary>
        public static string QueueToTheLandRefusedReport_NotificationHeader {
            get {
                return ResourceManager.GetString("QueueToTheLandRefusedReport_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем Вам, что Вы поставлены в очередь для получения земельного участка под индивидуальное жилищное строительство от {1} под №{2}..
        /// </summary>
        public static string QueueToTheLandStateInQueueReport_NotificationBody {
            get {
                return ResourceManager.GetString("QueueToTheLandStateInQueueReport_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИЗВЕЩЕНИЕ 
        /// О ПОСТАНОВКЕ В ОЧЕРЕДЬ ДЛЯ ПОЛУЧЕНИЯ ЗЕМЕЛЬНОГО УЧАСТКА ПОД  ИНДИВИДУАЛЬНОЕ ЖИЛИЩНОЕ СТРОИТЕЛЬСТВО.
        /// </summary>
        public static string QueueToTheLandStateInQueueReport_NotificationHeader {
            get {
                return ResourceManager.GetString("QueueToTheLandStateInQueueReport_NotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извещение 
        /// о приеме документов на оказание услуги
        /// &quot;{0}&quot;.
        /// </summary>
        public static string ReceptionNotification_HeaderText {
            get {
                return ResourceManager.GetString("ReceptionNotification_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет приложенных документов.
        /// </summary>
        public static string ReceptionNotification_NotAttachmentsDocuments {
            get {
                return ResourceManager.GetString("ReceptionNotification_NotAttachmentsDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0}, сообщаем, что Ваше заявление от {1} [{2}] №{3} на услугу &quot;{4}&quot; принято в работу со следующим списком приложенных документов:{6} {5}.
        /// </summary>
        public static string ReceptionNotification_NotificationText {
            get {
                return ResourceManager.GetString("ReceptionNotification_NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель:{0} {1} {2}.
        /// </summary>
        public static string ReceptionNotificationl_ExecutorName {
            get {
                return ResourceManager.GetString("ReceptionNotificationl_ExecutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о регистрации заявления по услуге «{0}».
        /// </summary>
        public static string RegistrationNotification_HeaderText {
            get {
                return ResourceManager.GetString("RegistrationNotification_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0}, уведомляем Вас о том, что ваше заявление на услугу «{1}» зарегистрировано от {2} [{3}] №{4}..
        /// </summary>
        public static string RegistrationNotificationText {
            get {
                return ResourceManager.GetString("RegistrationNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата направления.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название ДДО.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родителям необходимо прибыть в дошкольную организацию и зарегистрировать направление в течение 5-и рабочих дней.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес регистрации.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата постановки  на учет в МЖК.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата подачи заявки.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Настоящая справка выдана гр.(ке): {0} проживающему(ей) в {1} в том, что он(она) согласно решению акима (город, район) №{2} от {3} действительно назначен(а) опекуном над:.
        /// </summary>
        public static string TrusteeshipCertificatesIssueConfirmNotification_Text {
            get {
                return ResourceManager.GetString("TrusteeshipCertificatesIssueConfirmNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Базе данных опекунов (попечителей)  по городу Астана Вы не значитесь..
        /// </summary>
        public static string TrusteeshipCertificatesIssueRefuseNotification_Fill_Reason {
            get {
                return ResourceManager.GetString("TrusteeshipCertificatesIssueRefuseNotification_Fill_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} уведомляем Вас о том, что Вам отказано в выдаче справки по опеке и попечительству над {1} {2} года рождения и над его (ее) имуществом..
        /// </summary>
        public static string TrusteeshipCertificatesIssueRefuseNotification_Text {
            get {
                return ResourceManager.GetString("TrusteeshipCertificatesIssueRefuseNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Уважаемый(ая) {0} сообщаем, что Вам отказано в оказании государственной услуги «Установление опеки или попечительства над ребенком-сиротой (детьми-сиротами) и ребенком (детьми), оставшимися без попечения родителей» от {1} под № {2}.
        /// </summary>
        public static string TrusteeshipMatchingDenyNotification_Text {
            get {
                return ResourceManager.GetString("TrusteeshipMatchingDenyNotification_Text", resourceCulture);
            }
        }
    }
}
