//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.ServiceNameResources", typeof(ServiceNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение выплаты пособия опекунам или попечителям на содержание ребенка-сироты (детей-сирот) и ребенка (детей), оставшегося без попечения родителей.
        /// </summary>
        public static string AllowancePayments {
            get {
                return ResourceManager.GetString("AllowancePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача архивных справок.
        /// </summary>
        public static string ArchiveTranscript {
            get {
                return ResourceManager.GetString("ArchiveTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка на учет и очередность граждан, нуждающихся в жилье из государственного жилого фонда.
        /// </summary>
        public static string CitizensInNeedHousing {
            get {
                return ResourceManager.GetString("CitizensInNeedHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка на очередь детей дошкольного возраста (до 7 лет) для направления в детские дошкольные организации.
        /// </summary>
        public static string DayCareQueue {
            get {
                return ResourceManager.GetString("DayCareQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием документов в рамках Программы развития регионов до 2020 года по направлению «Жилье» акционерного общества «Жилищный строительный сберегательный банк Казахстана».
        /// </summary>
        public static string Housing2020 {
            get {
                return ResourceManager.GetString("Housing2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение жилищной помощи.
        /// </summary>
        public static string HousingAssistance {
            get {
                return ResourceManager.GetString("HousingAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача справок в пенсионные фонды и в территориальные подразделения Комитета дорожной полиции МВД для оформления наследства несовершеннолетним детям.
        /// </summary>
        public static string ProbateMinorsToMVD {
            get {
                return ResourceManager.GetString("ProbateMinorsToMVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача справок в пенсионные фонды для оформления наследства несовершеннолетним детям.
        /// </summary>
        public static string ProbateMinorsToPensionFound {
            get {
                return ResourceManager.GetString("ProbateMinorsToPensionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка в очередь для получения земельного участка под индивидуальное жилищное строительство.
        /// </summary>
        public static string QueueToTheLand {
            get {
                return ResourceManager.GetString("QueueToTheLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием граждан.
        /// </summary>
        public static string ReceptionOfCitizens {
            get {
                return ResourceManager.GetString("ReceptionOfCitizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установление опеки или попечительства над ребенком-сиротой (детьми-сиротами) и ребенком (детьми), оставшимися без попечения родителей.
        /// </summary>
        public static string Trusteeship {
            get {
                return ResourceManager.GetString("Trusteeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача справок по опеке и попечительству.
        /// </summary>
        public static string TrusteeshipCertificatesIssue {
            get {
                return ResourceManager.GetString("TrusteeshipCertificatesIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация и постановка на учет безработных граждан.
        /// </summary>
        public static string UnemployedRegistration {
            get {
                return ResourceManager.GetString("UnemployedRegistration", resourceCulture);
            }
        }
    }
}
