//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrusteeshipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrusteeshipResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESA.Resources.TrusteeshipResources", typeof(TrusteeshipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение выплаты пособия опекунам.
        /// </summary>
        public static string AllowanceOfPayments {
            get {
                return ResourceManager.GetString("AllowanceOfPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласование решения Назначить выплату пособия опекунам или попечителям.
        /// </summary>
        public static string AllowancePaymentAllowStep {
            get {
                return ResourceManager.GetString("AllowancePaymentAllowStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласование решения Отказать в назначении выплаты пособия опекунам или попечителям.
        /// </summary>
        public static string AllowancePaymentDenyStep {
            get {
                return ResourceManager.GetString("AllowancePaymentDenyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначить выплату пособия опекунам.
        /// </summary>
        public static string AllowPaymentTask {
            get {
                return ResourceManager.GetString("AllowPaymentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить опеку или попечительство.
        /// </summary>
        public static string AllowTrusteeshipTask {
            get {
                return ResourceManager.GetString("AllowTrusteeshipTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать в назначении выплаты пособия опекунам.
        /// </summary>
        public static string DenyPaymentTask {
            get {
                return ResourceManager.GetString("DenyPaymentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать в выдаче справки.
        /// </summary>
        public static string DenyTrusteeshipCertTask {
            get {
                return ResourceManager.GetString("DenyTrusteeshipCertTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать в установлении опеки или попечительства.
        /// </summary>
        public static string DenyTrusteeshipTask {
            get {
                return ResourceManager.GetString("DenyTrusteeshipTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия договора об открытии лицевого счета на имя опекуна или попечителя в банке второго уровня или в организации, имеющей лицензию Национального банка Республики Казахстан на осуществление отдельных видов банковских операций.
        /// </summary>
        public static string DocumentAccountNumber {
            get {
                return ResourceManager.GetString("DocumentAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия свидетельства о рождении ребенка (детей) в случае рождения ребенка до 13 августа 2007 года либо за пределами Республики Казахстан.
        /// </summary>
        public static string DocumentBirthCert {
            get {
                return ResourceManager.GetString("DocumentBirthCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронные копии документов о доходах ребенка (детей), подтверждающие получение государственных социальных пособий и иных социальных выплат, алиментов, сведения об имеющихся доходах от имущества ребенка (детей).
        /// </summary>
        public static string DocumentChildIncomes {
            get {
                return ResourceManager.GetString("DocumentChildIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия удостоверения личности.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия документов, подтверждающих факт отсутствия попечения над ребенком единственного или обоих родителей (свидетельство о смерти, решение суда о лишении родителей родительских прав, ограничении их в родительских правах, признании родителей безвестно отсутствующими, недееспособными (ограниченно дееспособными), объявлении их умершими, приговор суда об отбывании родителями наказания в местах лишения свободы, документы, подтверждающие розыск родителей, отобрание ребенка (детей) у родителей, нахожде [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DocumentMiscTrusteeship {
            get {
                return ResourceManager.GetString("DocumentMiscTrusteeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to электронная копия решения местного исполнительного органа о назначении опекуном или попечителем.
        /// </summary>
        public static string DocumentTrusteeship {
            get {
                return ResourceManager.GetString("DocumentTrusteeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-попечительство.
        /// </summary>
        public static string EGuardianship {
            get {
                return ResourceManager.GetString("EGuardianship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдать справку.
        /// </summary>
        public static string GiveTrusteeshipCertTask {
            get {
                return ResourceManager.GetString("GiveTrusteeshipCertTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если заявитель не указал в поле «Члены семьи заявителя» супруга(у), то документ: {0} - является обязательным для загрузки.
        /// </summary>
        public static string MsgLoadDocIfFamMembers {
            get {
                return ResourceManager.GetString("MsgLoadDocIfFamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если заявитель указал в поле «Члены семьи заявителя» супруга(у), то документ: {0} - является обязательным для загрузки.
        /// </summary>
        public static string MsgLoadDocIfMarried {
            get {
                return ResourceManager.GetString("MsgLoadDocIfMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать.
        /// </summary>
        public static string ProcessedStateDeny {
            get {
                return ResourceManager.GetString("ProcessedStateDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить.
        /// </summary>
        public static string ProcessedStateInstall {
            get {
                return ResourceManager.GetString("ProcessedStateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string ProcessedStateNone {
            get {
                return ResourceManager.GetString("ProcessedStateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для данного состояния не реализован шаг процессинга.
        /// </summary>
        public static string ProcessStepNotImplemented {
            get {
                return ResourceManager.GetString("ProcessStepNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина снятия статуса опекуна или попечителя.
        /// </summary>
        public static string ReasonForRemovalOfTrustee {
            get {
                return ResourceManager.GetString("ReasonForRemovalOfTrustee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ по услуге.
        /// </summary>
        public static string ServiceRefused {
            get {
                return ResourceManager.GetString("ServiceRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН опекуна.
        /// </summary>
        public static string TrusteeIIN {
            get {
                return ResourceManager.GetString("TrusteeIIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принятие решения по услуге.
        /// </summary>
        public static string TrusteeshipCertConfirmStep {
            get {
                return ResourceManager.GetString("TrusteeshipCertConfirmStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласование решения Установить опеку или попечительство.
        /// </summary>
        public static string TrusteeshipProcessAllowStep {
            get {
                return ResourceManager.GetString("TrusteeshipProcessAllowStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласование решения Отказать в установлении опеки или попечительства.
        /// </summary>
        public static string TrusteeshipProcessDenyStep {
            get {
                return ResourceManager.GetString("TrusteeshipProcessDenyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина оформления опеки или попечительства.
        /// </summary>
        public static string TrusteeshipReason {
            get {
                return ResourceManager.GetString("TrusteeshipReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение о назначении пособия опекуну или попечителю на содержание ребенка-сироты (детей-сирот) и ребенка (детей), оставшегося без попечения родителей, либо мотивированный отказ.
        /// </summary>
        public static string TrusteeshipServiceResult {
            get {
                return ResourceManager.GetString("TrusteeshipServiceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановление о назначении опеки.
        /// </summary>
        public static string TrusteeshipStatement {
            get {
                return ResourceManager.GetString("TrusteeshipStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН опекаемого.
        /// </summary>
        public static string WardIIN {
            get {
                return ResourceManager.GetString("WardIIN", resourceCulture);
            }
        }
    }
}
